basePath: /login
definitions:
  User.Login:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  User.Message:
    properties:
      message:
        type: string
    type: object
  jwt_func.RetornoVerificar:
    properties:
      validToken:
        type: boolean
    type: object
  jwt_func.Verfica:
    properties:
      token:
        type: string
    type: object
host: 172.23.58.10:8006
info:
  contact: {}
  description: Gerencia o sistema de autenticação e geração de tokens (jwt)
  title: Login - Jwt - API
  version: "1.0"
paths:
  /login/create:
    post:
      consumes:
      - application/json
      description: Pega o username e password e cria
      operationId: createUser
      parameters:
      - description: Credenciais do usuário
        in: body
        name: User.Login
        required: true
        schema:
          $ref: '#/definitions/User.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User.Login'
      summary: Cria Usuário
  /login/delete:
    post:
      consumes:
      - application/json
      description: Pega o username e senha e exclui
      operationId: deleteUser
      parameters:
      - description: Credenciais do usuário
        in: body
        name: User.Login
        required: true
        schema:
          $ref: '#/definitions/User.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User.Message'
      summary: Deleta Usuário
  /login/token:
    post:
      consumes:
      - application/json
      description: Faz login com nome de usuário e senha
      operationId: logar
      parameters:
      - description: Credenciais do usuário
        in: body
        name: userCredentials
        required: true
        schema:
          $ref: '#/definitions/User.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jwt_func.Verfica'
      summary: Logar usuário
  /login/validador:
    post:
      consumes:
      - application/json
      description: Pega o token e verifica se é válido
      operationId: verificadorJwt
      parameters:
      - description: Token
        in: body
        name: token
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jwt_func.RetornoVerificar'
      summary: Verifica Jwt Token
schemes:
- http
- https
swagger: "2.0"
